### ISSUE TITLE
Playground view should also display the graph information

### ISSUE THREAD

**Issue by annaritz** [FlickerSoul/Graphery#108]
**Is your improvement request related to a problem? Please describe.**
Users should be able to see the graph information in the playground view.  Right now it's just the code base and the network. 

**Describe the solution you'd like**
A quick solution is to add the same `...` button in the bottom left of the code editor pane, just like the tutorial view.  Have the same popup flash when the playground is opened.  _maybe default to the graph information page?_

**Describe alternatives you've considered**
A longer-term solution is to have the same three panels as the tutorial, but the tutorial pane will be replaced with the graph information. 

**Additional context**
Some of the graph information pages have a lot of text, and there's no default way that a user sees that information along with the actual network.

**Comment by FlickerSoul** [comment]
I could add a button to the editor section and show the graph info as a popup. Does this sound right? As for the long term solution, my opinion is that the graph page serves as a playground, and the users' main interaction will happen in the editor. Am I misunderstanding anything? I would keep the information as a popup so that it servers as an addon, that is when users need it, it will be there, and does not consume too much attention and space.

**Comment by FlickerSoul** [comment]
The graph info should serve as a "splash screen" after users entering a graph playground and before users starting coding. A specific implementation will be discussed in the next few days.

**Comment by FlickerSoul** [comment]
fixed in 4e6b24eff0136da08edf32cd87ecf6af5fc10463
